### PR TITLE
Issue #149: Add link validataions

### LINKED ISSUE #149: Add validation for connection in out vs flow in out for dataflows
Currently this is only checking IO of flows, but it is also assuming the connections are to and from flows. 

This is NOT the case, and it should also check the type of the step (flow vs connector), and also determine its particular connection requirements.

### LINKED ISSUE #166: Bug all readers eg sql should have no flow inputs

### PR DESCRIPTION
**Pull request by jaypha**
Resolve #149 
Resolves #166 

Add methods to step to validate input and output links.

### CODE REVIEW

**Comment by jaypha** [comment]
I'm looking for a way to avoid multiple database reads.

**Comment by jaypha** [comment]
Screenshot from 2022-06-09 09-58-47

**Comment by brendanheywood** [comment]
@jaypha can you please also highlight any nodes which are not valid in red here:

https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/local/step/base_step.php#L343-L344

**Comment by jaypha** [comment]
Screenshot from 2022-06-09 14-04-44
Screenshot from 2022-06-09 14-04-58

**Pull request merged**
